[workspace]
members = [
    "ports/cef",
    "ports/geckolib",
    "ports/servo",
]

[profile.dev]
codegen-units = 4

[profile.release]
opt-level = 3
# Uncomment to profile on Linux:
# debug = true
# lto = false


# If you need to temporarily test Servo with a local fork of some upstream
# crate, add that here. Use the form:
#
#     <crate> = { path = "/path/to/local/checkout" }

[replace]
"https://github.com/servo/webrender#0.48.0" = { git = "https://github.com/szeged/webrender/", branch = "gfx-wr-8fd634-0727" }
"https://github.com/servo/webrender#webrender_api:0.48.0" = { git = "https://github.com/szeged/webrender/", branch = "gfx-wr-8fd634-0727" }
