[workspace]
members = [
    "ports/cef",
    "ports/geckolib",
    "ports/servo",
]

[profile.dev]
codegen-units = 4

[profile.release]
opt-level = 3
# Uncomment to profile on Linux:
# debug = true
# lto = false

"webrender" = { git = 'https://github.com/szeged/webrender', branch='WR_53_dx11' }
"webrender_api" = { git = 'https://github.com/szeged/webrender', branch='WR_53_dx11' }
